### ISSUE TITLE
System.Index, System.Range from C#8

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#104]
https://github.com/sdcb/Sdcb.System.Range
https://github.com/dotnet/coreclr/pull/20899

**Comment by theraot** [comment]
This won't work: https://github.com/sdcb/Sdcb.System.Range/blob/master/Sdcb.System.Range/RangeExtensions.cs as the readme says you need a particular version of Roslyn: https://github.com/sdcb/Sdcb.System.Range/blob/master/README.md - or newer? I failed to make an get_IndexerExtension method work in sharplab.io

**Comment by NN---** [comment]
This should be enough
https://gist.github.com/meziantou/177600eab9961f3296060d1b8bcd5f40

According to this article
https://www.meziantou.net/how-to-use-csharp-8-indices-and-ranges-in-dotnet-standard-2-0-and-dotn.htm

**Comment by NN---** [comment]
While trying to port Index and Range from: https://github.com/rsdn/CodeJam/pull/138/files

I encountered several issues.
1. Range has a method returning ValueTuple which requires TupleElementNamesAttribute.
The question is whether it should come from.
Sounds like dependency on System.ValueTuple for appropriate framework version is the solution.
2. Use of HashCode.
It is not defined in Theraot at all, however it is defined in Microsoft.Bcl.
The issue rises only in tests, I do not think adding Microsoft.Bcl dependency to Theraot is a good idea, theefore the solution is to use extern alias for Microsoft.Bcl or if possible remove completely.

**Comment by NN---** [comment]
2. fixed by https://github.com/theraot/Theraot/commit/4a381e7dabab0b40b5b5b1c7c19ac3eae5ab4ad8

**Comment by NN---** [comment]
@theraot Can you push an updated NuGet ?
