### ISSUE TITLE
SafeBuffer, SafeRegistryHandle, UnmanagedMemoryAccessor for .NET 2.0 & 3.5

### ISSUE THREAD

**Issue by dahall** [theraot/Theraot#109]
I have the code for these types tested and working. I can put them in my project (Vanara) or this one. Since they are backward compatibility focused, do you have any issue with me doing a PR to add them to this project?

**Comment by dahall** [comment]
`UnmanagedMemoryAccessor`, I believe, would go in the existing folder `System/IO`. `SafeBuffer` is in the `System.Runtime.InteropServices` namespace. Would you have me create a folder named `InteropServices` under `System/Runtime`? For `SafeRegistryHandle`, it is in the `Microsoft.Win32.SafeHandles` namespace. It is not obvious to me where that would go. Please advise.

**Comment by dahall** [comment]
Having just added the code to my branch, it appears that the current assembly does not support `unsafe` code. How do you feel about enabling it?

**Comment by theraot** [comment]
I would prefer these on a different assembly.

Consider: https://stackoverflow.com/a/2299438/402022
