### ISSUE TITLE
Expression.GetDelegateType isn't available for .NET Framework 3.5

### ISSUE THREAD

**Issue by lbmaian** [theraot/Theraot#110]
Hi, I see that Theraot has an equivalent for the official .NET Framework 4.0+ Expression.GetDelegateType in its LambdaExpression.cs. However it's only available for .NET versions LESS than .NET Framework 3.5, not for 3.5 itself.

Since 3.5 does already defines Expression et al classes, can you add an ExpressionEx class that at least has the static GetDelegateType method? That way, those stuck on .NET Framework 3.5 like me have some recourse, as that particular method has functionality such as allowing ref parameter types that can't be done via Expression.GetActionType/Expression.GetFuncType.

~~On a side note, It's odd that the GetDelegateType function is on LambdaExpression rather than on Expression itself, where it is officially, considering that in <3.5 builds, you have to define both classes anyway.~~ edit: Just realized that although GetDelegateType is in LambdaExpression.cs, it's still defined in the Expression class, which is a partial class there.

Thanks!

**Comment by theraot** [comment]
As you have seen GetDelegateType uses simply delegates to DelegateHelpers. So, I believe DelegateHelpers is ultimately what you want. DelegateHelpers is internal, I can move it to another namespace, add proper validations and make it available.

Meanwhile, you can use Theraot.Reflection.DelegateBuilder, which is what DelegateHelpers uses.

**Comment by lbmaian** [comment]
Yes, moving DelegateHelpers to a non-System namespace and made public would suffice.

However, DelegateBuilder by itself doesn't suffice, since it can't automatically create custom delegates when there's not a corresponding Action/Func type available, which happens when any parameter types are by ref or if there are too many parameters.

**Comment by theraot** [comment]
DelegateHelper.GetDelegateType available

Nuget version 3.1.0

**Comment by lbmaian** [comment]
Thanks!
