### ISSUE TITLE
.NET 4.7.1 Targeting

### ISSUE THREAD

**Issue by theraot** [theraot/Theraot#116]
There is a conflict with Linq in .NET 4.7.1: [Append](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.append) and [Prepend](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.prepend) were added on this version.

#114, #115

**Comment by NN---** [comment]
Do you need 4.6.2 and 4.6.1 ?
https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#v461
https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#v462

**Comment by theraot** [comment]
I tested if there was any conflict with them in the built, none at the moment.

**Comment by NN---** [comment]
Ok. great

**Comment by NN---** [comment]
When do you merge and update nuget ?

**Comment by theraot** [comment]
Nuget Version 3.1.1
