### ISSUE TITLE
SourceLink support

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#119]
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

Just add package and relevant properties, see: https://github.com/rsdn/CodeJam/commit/f71645af713a27e8e299e8ab329b2ff5381e3e5d#diff-29625df1d8c0f40d09db6e8f2cdfb7ecR30

```xml
	<PropertyGroup>
		...
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
	</ItemGroup>
```

**Comment by theraot** [comment]
Nuget version 3.1.3 published along side a symbol package.
