### ISSUE TITLE
Using Theraot on Framework 2.0, in Webform.aspx without codebehind not working :(

### ISSUE THREAD

**Issue by cesarcamps** [theraot/Theraot#122]
I create a simple website, on vs 2019, using framework 2.0, but give error 

Error	CS8023	Feature 'query expression' is not available in C# 2. Please use language version 3 or greater.	7_Default.aspx	C:\Temp\website\Default.aspx	13	Active

[website.zip](https://github.com/theraot/Theraot/files/5137573/website.zip)

![image](https://user-images.githubusercontent.com/39138774/91468209-a8d09300-e85f-11ea-8f8e-f3a4d5b61d35.png)

**Comment by cesarcamps** [comment]
Sorry, using Theraot 3.1.5, on target framework 2.0.

**Comment by NN---** [comment]
You mix C# language version and .NET Framework version.
They don't correlate 1 to 1.
You can use C# 9 even with .NET Framework 2.0 .

What you configured is using C# language 2 which doesn't support LINQ comprehension.
You must change to C# language 3 or above to use this syntax.

**Comment by theraot** [comment]
With Theraot.Core you should be able to use newer versions of C# on older .NET Frameworks. Go ahead and change the language version, you should be able to find the option in project properties. The compiler will then look for the types needed to make Linq work, which are not available in .NET Framework 2.0, yet Theraot.Core provides them.

**Comment by cesarcamps** [comment]
I there.
I am using a website, where can i set language version?? I do not see it in project's option 

![image](https://user-images.githubusercontent.com/39138774/91489586-0c1ded80-e87f-11ea-8457-7d9250159c40.png)

**Comment by cesarcamps** [comment]
Beside, when i host it, in a IIS with framework 2.0 configured, this error poped out
Sorry by my question, but i do not know where to ask (english is not my mother language).

![image](https://user-images.githubusercontent.com/39138774/91489749-4dae9880-e87f-11ea-82cb-b1e962b718d3.png)

**Comment by theraot** [comment]
**Option 1**

For the web project you have to modify Web.config.

I tried with your zip, adding the following inside Web.config configuration worked for me:

```
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp"
                extension=".cs"
                warningLevel="4"
                type="Microsoft.CSharp.CSharpCodeProvider, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
        <providerOption name="CompilerVersion" value="v3.5" />
        <providerOption name="WarnAsError" value="false" />
      </compiler>
    </compilers>
  </system.codedom>
```

That should enable Linq.

---
**Option 2**

For what I read, you should also be able to use Roslyn (DotNetCompilerPlatform) instead. It seems it would require some manual deploy.

You can install DotNetCompilerPlatform version 1.0.0.0 from Nuget (I haven't tested which is the newest version you can install). Temporarily remove the problematic code (make it comments), so you can build the website, and the nuget is downloaded, afterwards, you would set the following in web.config (instead of the code above):

```
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
  </system.codedom>
```

Once you have it, Visual Studio will tell you it can't find "\bin\roslyn\csc.exe". You can get csc et.al. from the nuget Microsoft.Net.Compilers. Yet installing it did not solve the issue for me, instead I downloaded the nuget, extracted it, and got the files from the tools folder in there. That is the manual part. I guess I must be missing something. There are plenty of web search results about setting Roslyn in web.config. Hopefully you have better luck.

**Comment by cesarcamps** [comment]
> **Option 1**
> 
> For the web project you have to modify Web.config.
> 
> I tried with your zip, adding the following inside Web.config configuration worked for me:
> 
> ```
>   <system.codedom>
>     <compilers>
>       <compiler language="c#;cs;csharp"
>                 extension=".cs"
>                 warningLevel="4"
>                 type="Microsoft.CSharp.CSharpCodeProvider, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
>         <providerOption name="CompilerVersion" value="v3.5" />
>         <providerOption name="WarnAsError" value="false" />
>       </compiler>
>     </compilers>
>   </system.codedom>
> ```
> 
> That should enable Linq.
> 
> **Option 2**
> 
> For what I read, you should also be able to use Roslyn (DotNetCompilerPlatform) instead. It seems it would require some manual deploy.
> 
> You can install DotNetCompilerPlatform version 1.0.0.0 from Nuget (I haven't tested which is the newest version you can install). Temporarily remove the problematic code (make it comments), so you can build the website, and the nuget is downloaded, afterwards, you would set the following in web.config (instead of the code above):
> 
> ```
>   <system.codedom>
>     <compilers>
>       <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
>   </system.codedom>
> ```
> 
> Once you have it, Visual Studio will tell you it can't find "\bin\roslyn\csc.exe". You can get csc et.al. from the nuget Microsoft.Net.Compilers. Yet installing it did not solve the issue for me, instead I downloaded the nuget, extracted it, and got the files from the tools folder in there. That is the manual part. I guess I must be missing something. There are plenty of web search results about setting Roslyn in web.config. Hopefully you have better luck.

Yes!!! With option 1  !!!
Thanx's!
