### ISSUE TITLE
Provide a IReadOnlySet matching .NET 5.0

### ISSUE THREAD

**Issue by theraot** [theraot/Theraot#125]
Documentation: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlyset-1?view=net-5.0

Should be implemented by HashSetEx and SortedSetEx

**Comment by NN---** [comment]
Oh, they finally fixed this :)
I am so excited for .NET 5.0 release.

**Comment by theraot** [comment]
NuGet 3.2.0.
