### ISSUE TITLE
Any plans to backport System.Diagnostics.Contracts?

### ISSUE THREAD

**Issue by Ghopper21** [theraot/Theraot#13]
Hi theraot. This compatibility pack looks wonderful. As a Unity3D user, I'm keen to see how this can help bridge the gap between Unity's older .NET support and the latest goodies.

I was bummed to see `System.Diagnostics.Contracts` not on your list. I'm wondering -- do you have any plans to back port that? If so, I'd certainly be willing to be a test user or help however I can.

**Comment by theraot** [comment]
As it stands I have no plans for Contracts.

This is my reasoning: Contracts has static checks and runtime checks. The static checks require tooling support to enforce them at compile time... maybe that's doable in VS 2015 via roselyn... also some runtime checks requires to rewrite the emitted code (PostSharp style* - I don't know if that is doable with Unity) without the proper tooling support this wont be transparent. And finally there are the rest of the runtime checks which are a bunch of precondition.

*: you write postconditions before but they are checked later.

I've been trying to focus on Tasks - code still stuck in the develop branch - I may have another look into Contracts later on... yet I can't put much time on this project right now.

That doesn't mean you are totally out of luck, if all you want is the preconditions you can try using http://conditions.codeplex.com/ which will help you write precondition checked at runtime.

**Comment by Ghopper21** [comment]
Gotcha, thanks for the quick reply, yeah Contracts are tricky given the special static and runtime checks...

And thanks for the tip on CuttingEdge.Conditions -- looks like it provides both pre- and post-conditions. I can probably roll my own invariant checker based on the post-conditions.

**Comment by Ghopper21** [comment]
P.S. It seems CuttingEdge.Conditions is no longer maintained but there is a fork with recent activity [here](https://github.com/ghuntley/Conditions).

**Comment by theraot** [comment]
I'll have a partial implementation of Contracts because I'll start to import code from Microsoft's reference implementation.

**Comment by theraot** [comment]
Partial implementation of Contracts has moved to the Develop branch - this implementation has Assert, Require and Invariant - the code is mainly taked form Mono's copy of Microsoft's code. Only Assert has a reliable effect - both Require and Invariant will require assembly rewriting (which I haven't tested, and I don't plan to support) - so they are fancy* noops.

None of the Contract methods will trigger UI - but they may trigger the debugger if one is attached.

*: There is a limited contract notification mechanism via the [ContractFailed](https://msdn.microsoft.com/en-us/library/vstudio/system.diagnostics.contracts.contract.contractfailed(v=vs.100).aspx) event.

**Comment by theraot** [comment]
Pushing to master, will soon be in the nuget.

If you give it a try and find any problems, let me know, create a new issuse.

I'm closing this.

**Comment by Ghopper21** [comment]
Thanks, will do.
