### ISSUE TITLE
Hello? Feedback?

### ISSUE THREAD

**Issue by theraot** [theraot/Theraot#14]
I want to know from people that has used Theraot.Core...

What has been your experience with it?
What features are they interested in?
Has you used the Nuget Package?
Are you interested in seeing bringing Task / async in .NET 2.0?
Are you intersted in in-memory transaction? [which I did cut out from the nuget*]

*: They are in FAT builds only. Even doing that expression has put the library over 1MB.

**Comment by cician** [comment]
>> I want to know from people that has used Theraot.Core..
I'm porting libgit2sharp to Unity3D, which currently only supports a subset of .net libraries, mostly at 3.5 level. Actually libgit2sharp switched not too long ago from .net 3.5 to 4.0. They used a few helper classes similar to those found in Theraot.Core, but limited to those used by the library.

>>What has been your experience with it?
Theraot just made my life a lot easier, just a few hours, and I'm done, probably...

>>What features are they interested in?
I'm mostly covered already. I missed only a few little bits in my venture:
- Path.Combine(params string[])
- Environment.Is64BitProcess
- IntPtr.Add
- string.Join(string, string, string)? maybe the StringHelper(string, string[]) signature is wrong? (Missing "params" modifier)
- Not exactly missing, but AggregateException is defined in System.Threading. Shouldn't it be in System namespace directly?

>>Has you used the Nuget Package?
Yes. I cloned the git repo too, just for reference.

>>Are you interested in seeing bringing Task / async in .NET 2.0?
>>Are you intersted in in-memory transaction? [which I did cut out from the nuget*]
>>*: They are in FAT builds only. Even doing that expression has put the library over 1MB.
Not necessary for my limited purpose.

Thanks a lot for this library!

**Comment by theraot** [comment]
@cician Thank you. Yes you are right about StringHelper.Join and AggregateException - I think I have a workaround for Is64BitProcess, and will look into the rest, they surely will need some testing. Will be working on it.

All feedback is welcome.

**Comment by theraot** [comment]
@cician Thank you. Yes you are right about StringHelper.Join and AggregateException.

I have implemented your requests on the Develop branch. StringHelper.Join now includes the `params` modifier and AggregateException was moved to `System`. For the others see:
- [`PathHelper`](https://github.com/theraot/Theraot/blob/Develop/Core/Theraot/Core/PathHelper.cs)
- [`EnvironmentHelper`](https://github.com/theraot/Theraot/blob/Develop/Core/Theraot/Core/EnvironmentHelper.cs)
- [`IntPtrHelper` and `UIntPtrHelper`](https://github.com/theraot/Theraot/blob/Develop/Core/Theraot/Core/IntPtrHelper.cs)

Will move to master soon.

All feedback is welcome.

**Comment by cician** [comment]
Thanks again for your hard work. I've switched to Develop branch of Theraot from git for now. Changes in my fork of libgit2sharp reduced to just about 20 lines of code! This should help me follow their upstream much easier in the long term.

ps.: I had to remove these two lines from .csproj files to compile in MonoDevelop. Everything looks fine without it as there's a corresponding define in target build (I'm using NET35FAT).

```
iff --git a/Core/Core.csproj b/Core/Core.csproj
index 1f50a47..c0a5b05 100644
--- a/Core/Core.csproj
+++ b/Core/Core.csproj
@@ -196,10 +196,6 @@
     <LangVersion>default</LangVersion>
   </PropertyGroup>
   <PropertyGroup>
-    <DefineConstants Condition=" !$(DefineConstants.Contains(';NET')) ">$(DefineConstants);$(TargetFrameworkVersion.Replace("v", "NET").Replace(".", ""))</DefineConstants>
-    <DefineConstants Condition=" $(DefineConstants.Contains(';NET')) ">$(DefineConstants.Remove($(DefineConstants.LastIndexOf(";NET"))));$(TargetFrameworkVersion.Replace("v", "NET").Replace(".", ""))</DefineConstants>
-  </PropertyGroup>
-  <PropertyGroup>
     <SignAssembly>true</SignAssembly>
   </PropertyGroup>
   <PropertyGroup>
diff --git a/Tests/Tests.csproj b/Tests/Tests.csproj
index cf8e6cc..1b71554 100644
```

**Comment by theraot** [comment]
@cician those lines are needed for batch building the libraries across the various target frameworks. They make sure that the right compilation constants are in for each one. They work on Xamarin Studio - although not as smoothly as in Visual studio - the support is improving for the version 6 of Xamarin (currently on preview).

In your case, since you are using NET35FAT you will need NET35 and FAT defined and the target framework set to .Net 3.5 or .Net 3.5 Client Profile.

**Comment by cician** [comment]
OK, thanks. I'll retest with either Xamarin Studio/monodevelop 6 when it's out or just switch to stable nuget build when these changes make it there.

**Comment by theraot** [comment]
@cician moved to master, nuget soon.

**Comment by LokiMidgard** [comment]
I just found your Project when I was told to bring a library that I've written to Net3.5.
I feard to rewrite everything without Tasks. (And I had a bunch of those).

> What has been your experience with it?
Untill now Everything just works :). Through I have just started using it.
> What features are they interested in?
Most of the functionality that I need was already there. I'll just added some methods to ```Stream``` like ```CopyTo``` and Task based async Methods.
> Has you used the Nuget Package?
Yes. makes it much easier to track all the used librarys (and there licensis)
> Are you interested in seeing bringing Task / async in .NET 2.0?
I hope I'll not have to write a .Net 2 library.
> Are you intersted in in-memory transaction? [which I did cut out from the nuget*]
Actually didn't know that it existed in .Net ^^

**Comment by dahall** [comment]
I have a [large PInvoke library](https://github.com/dahall/Vanara) and, until I found your library, had been doing all the backporting myself. I just added your NuGet package, removed all my backports, and it works! Tasks would be wonderful as today I have to use include directives to exclude async methods from earlier .NET versions.

**Comment by theraot** [comment]
@dahall I'm glad you find it useful.

Task is in the nuget package. Async works in all .NET framework versions. You may find a few things missing around .NET 3.5 (in Linq Expressions, no work around) and around .NET 4.0 (in Task, a TaskEx class is provided similar to TPL that will work across .NET versions).

If you need any missing API, or you run into any bug, please let me know and I'll work on it.

Coming soon: Performance improvements around CancellationTokens and Concurrent collections, also Partitions are underway.

**Comment by stazz** [comment]
Hi,

I am using Theraot.Core library in my projects (used by [UtilPack](https://github.com/stazz/UtilPack/tree/develop/Source/Code/UtilPack), of which all of my other project directly or indirectly depend on). Most of my projects are multi-targeted, and .NET Desktop 4 is one of the targets, since it is after all very complete framework by itself.

> What has been your experience with it?

So far so good - I'm surprised how little amount of work was needed to make things compile against .NET 4 as well as .NET Standard and .NET Core.

> What features are they interested in?

For me, mostly `async` stuff, which is missing from original .NET 4.

> Has you used the Nuget Package?

The CI pipelines for my project build everything within `microsoft/dotnet:2.2-sdk-alpine` container using `dotnet build` command, so using NuGet package is the only sane thing in there.

> Are you interested in seeing bringing Task / async in .NET 2.0?

No comment there, as lowest .NET Desktop version I use is 4.

> Are you intersted in in-memory transaction? [which I did cut out from the nuget*]

I don't think these things are responsibility of .NET framework, but rather libraries made by users. Transactionality has traditionally been really hard concept in imperative languages, so I am cautious with that.


A couple of questions of my own, if I may:
- How do you test that stuff works in .NET 4? Do you have dedicated WinXP VM for that? Is there some kind of container with .NET 4 (doubtful)? My "validation" so far has been only compilation - I trust that since it compiles against .NET 4, it will also work there. All of my test runs within CI pipeline are ran within the same container as they are built in.
- I have some suggestions/improvement ideas, which are conceptually small, should I open new issues for them or just ask here?

**Comment by theraot** [comment]
> How do you test that stuff works in .NET 4? Do you have dedicated WinXP VM for that? Is there some kind of container with .NET 4 (doubtful)? My "validation" so far has been only compilation - I trust that since it compiles against .NET 4, it will also work there. All of my test runs within CI pipeline are ran within the same container as they are built in.

Tests run on my machine (Windows 10) and on AppVeyor servers (they will detect tests written on some common test systems, or you can provide a custom script to run tests).

That comes with some caveats:

1. Some targets have received security updates, and .NET 3.5 had a service pack. I am not testing for the versions without those. I cannot provide those patches anyway.
2. Some API change behavior from version to version. For example LINQ Expressions on .NET Core when converted to string will use "**" for exponentiation instead of "^". In those cases I have to pick what behavior to mimic. I prefer .NET Framework behavior.
3. The Garbage Collector have changed, I would need an outdated machine to test against old Garbage Collectors. I will not rely in any of the changes. *Now, thinking about it, perhaps I should rework GCMonitor to use GC.WaitForPendingFinalizers.* Speaking of the Garbage Collector, ConditionalWeakTable is just a weak table on my backport. As far as I can tell, there is no way to mimic ephemerons on old targets.
4. I have discovered some discrepancies between documentation and implementation. Not really something that would introduce bugs, however I need to pick to follow the documentation or to follow what .NET actually does. I prefer to do what the documentation says.

However, testing has started to become a problem. Why? I need different test system versions for different targets to actually run tests in all of them, and I have not been able to automate this, meaning I can only do it on my machine. I have started writing a custom testing system for version 3.

> I have some suggestions/improvement ideas, which are conceptually small, should I open new issues for them or just ask here?

Either will work. Another alternative is to write to the email on my profile.

Please tell me of any API you are missing/want me to add.

You can consider any behavior that does not match MSDN a bug, and you can consider any conflict with a Microsoft NuGet a bug. If you have one of those conflicts, you would get a warning on build; `using` alias directive should serve as workaround. If you end up with an alias directive or conditional compilation around using directives because of my library, let me know, I should be fixing that.

**Comment by stazz** [comment]
Thank you for clarifying answer! I guess testing stuff like that is indeed difficult, considering that .NET Desktop is not side-by-side in nature at all, unlike .NET Core. I remember reading about that MS is cautious with even fixing bugs on .NET Desktop, as the fixes might break existing applications relying on buggy behaviour.

I'll open separate issue for the APIs to be added. 👍
