### ISSUE TITLE
Splitting the library -- Feedback?

### ISSUE THREAD

**Issue by theraot** [theraot/Theraot#15]
I'm considering to make backporting System.Core a separate assemby.

Reasoning: if I can provide all System.Core you could opt to not link System.Core and link Theraot.Core instead, this would allow me to provide (when completed) the full exprience for all the framework versions. In fact, it could allow me to target only .NET 2.0.

In particular, as it stands I cannot provide the missing expression in .NET 3.0 types becuase implementing them requires access to the internals of the framework. On the other hand .NET 2.0 has them because it doesn't have to link System.Core so there is no conflict there and I can provide the whole backend for expressions.

Something similar on an smaller scale happens with HashSet<T> with implements ISet<T> on .NET 2.0 and 3.0 then it .NET 3.5 it does not and in .NET 4.0 it does again. HashSet<T> is also on System.Core.

Of course this also means that the parts that are backports of the corlib (mscorlib) got to be deployed under the current schema because I don't pretend to fully replace it.

Edit: that also means that if you don't need the whole thing, you don't have to use the whole thing. I say that because I suspect that library size is a concern.

---

Besides what is mentioned above... I plan to move the code that has been only available on "FAT" builds to a new assembly that will focus on needles and transactions.

I also want to release some other code as separate libraries under the Theraot namespace...

---

Is this venture worthwhile? Or I'm just wasting my time?
Should I focus on continuing to back port Task? Expressions? the rest of System.Core? somethings else?

I want to have an idea of demand for this things...

<strike>[For the time being I'm taking some time off]</strike>

**Comment by dahall** [comment]
The only advantage I see to splitting the library would be assembly size. It is a little large now. I would recommend splitting it like Microsoft has done along the namespace lines with a small core library that would get referenced. For example, you could pull out `ValueTuple` and put it in `Theraot.ValueTuple`.

I do think that pulling Theraot.Core into its own package would be valuable.

**Comment by theraot** [comment]
@dahall That makes sense. I would have to be very careful on where I cut.

About the Theraot namespace, all that is there in the nuget is used to backport something. Although less of it is necesary for the most recent versions.

Perhaps strimmed down versions make sense for people who do not care to backport all the way to .NET 2.0 - for example, a lot of people are only going back to .NET 3.5 because they are stuck in old Unity3D versions, or only back to .NET 4.5 because they only target recent Windows versions. That could be a good place to start looking for potential cuts.

**Comment by dahall** [comment]
I wouldn't split it up by .NET version. I think that is one of the strengths of your project -- one package that brings all .NET versions to a level of compatibility. If anything, I would align the assemblies to their counterparts in the framework (e.g. mscorlib, System, System.Data, etc.).

**Comment by dahall** [comment]
You could also just leave it as it is. 🥇

**Comment by theraot** [comment]
@dahall pushed version 3.0.0

**Comment by dahall** [comment]
What key changes did you make that I should be testing against? Are there release notes somewhere? I looked, but didn't easily find them.

**Comment by theraot** [comment]
@dahall Well, I am a sham, did not write any. So, let us see, baring changes outsie of the System namespace...

- New code organization to make things easier to find: For most missing APIs with workarounds there are *TheraotExtensions classes with extension methods and *Ex classes where those won't do. These are the *Ex types:
  - System.Collections.Concurrent.PartitionerEx.Create<TSource>(IEnumerable<TSource>, EnumerablePartitionerOptions)
  - System.Collections.Generic.ComparerEx.Create<T>(Comparison<T>)
  - System.Collections.Generic.DictionaryEx (with IReadOnlyDictionary<TKey, TValue>)
  - System.Collections.Generic.HashSetEx (with IReadOnlyCollection<T> and ISet<T>)
  - System.Collections.Generic.ListEx (with IReadOnlyList<T>)
  - System.Collections.ReadOnlyCollectionEx<T> (with IReadOnlyList<T>)
  - System.Diagnostics.DebugEx.Fail (missing in .NET Standard 1.2)
  - System.Threading.Tasks.TaskEx (multiple missing APIs added since last stable release)
  - System.ArrayEx.Empty<T> (missing in .NET 4.5 and .NET Standard 1.2)
  - System.EnumEx.TryParse (missing .NET 4.0)
  - System.EnvironmentEx.Is64BitProcess (missing in .NET 3.5, .NET Core 1.1 and .NET Standard 1.6)
  - System.EventHandlerEx (TEventArgs contravariant)
  - System.IntPtrEx and System.UIntPtrEx (Add and Substract missing in .NET 3.5)
  - System.OperationCanceledExceptionEx (No CancellationToken in .NET 3.5)
  - System.StringEx (Concat and Join missing in .NET 3.5)
- Avoiding conflicts with the following Microsoft NuGets:
  - System.Diagnostics.Contracts
  - System.Dynamic.Runtime
  - System.Linq.Expressions
  - System.Linq.Queryable
  - System.Reflection
  - System.Reflection.TypeExtensions
  - System.Runtime
  - System.Runtime.InteropServices
  - System.Runtime.Numerics
  - System.Threading
  - System.Threading.Tasks.Extensions
  - System.Threading.Tasks.Parallel
  - System.Threading
  - System.Threading.Timer
  - System.ValueType
- Thread, ThreadPool, Timer et.al for .NET Standard 1.3
- Working reflection accross .NET Standard
- Added TaskFactory missing methods prior to .NET 4.0
- Improved SemaphoreSlim.AsyncWait on .NET 4.0 (less resource intensive, fixed edge cases)
- New TaskEx.FromWaitHandle  and TaskEx.FromCancellation
- Stream.*Async methods
- Added Serialization attributes and basic types (Serialization won't work in all platforms, but you won't have to put conditional compilation around the attributes)
- MethodImplOptionsEx allows to use AggressiveInlining when targeting .NET 2.0, it will work when the runtime supports it (also means no need for conditional compilation around the MethodImpl attribute)
- Fix for Linq Min and Max around NaN
- Fixes for BlockingCollection (fixed semaphore full exception, and follow Microsoft's behavior more closely)
- Added various non generic collection types
- Improved performance of concurrent collections
- Memory usage changes: arrays are pooled internally (that is not new), now the library will hold larger arrays (potentially more memory usage) and will not hold arrays of all types forever (potentially less memory usage on long runs)
- TaskScheduler.FromCurrentSynchronizationContext working
- Added Parallel.For

**Comment by dahall** [comment]
Thanks. That helps a lot. I understand pushing out the and bypassing documentation. I do it too often too.
