### ISSUE TITLE
Building library for NET 3.5 under VS2008

### ISSUE THREAD

**Issue by oznetmaster** [theraot/Theraot#18]
If the NET35 conditional variable is set, code is included in the compilation which is not valid for NET 3.5.

For instance:

`public delegate void Action<in T1, in T2, in T3, in T4, in T5>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
`

will not compile, because `in` is a C# 4.0 feature, and not available in C# 3.0 (NET 3.5).

**Comment by theraot** [comment]
I see,

Although this is not because of version .NET but because of the version of the language, I don't have conditional compilation for old language versions.

If you cannot run a newer version of Visual Studio you can still compile with Xamarin Studio with no problem.

**Comment by oznetmaster** [comment]
Also, NET35 includes code that uses default/optional parameters, which are not supported on NET35:

``        internal static string GetFailureMessage(ContractFailureKind failureKind, string conditionText = "")``

**Comment by theraot** [comment]
.NET 3.5 supports this, Visual Basic uses it. It is your compiler that is using an old version of the language, not the version of .NET

Considering the complexity of having conditional compilation for each combination of language version and framework version... are you suggesting to rewrite the code in ISO C#?

**Comment by oznetmaster** [comment]
Compiling for the Compact framework, which is a subset of NET 3.5, requires the use of VS2008 and C# 3.0.

I am well aware of the issues of language compatibility, since I am the person maintaining NUnit for the compact framework.

NUnit uses only C# 3.0 as its target language for any pre 4.0 capabilities.

**Comment by theraot** [comment]
I have been unable to test on Compact Framework, yet, I guess I can make build configuration for that

**Comment by oznetmaster** [comment]
I am fully able to test with the compact framework, since I have VS2008 installed, and use it constantly.

For NUnit we even have AppVeyor set up to build the compact framework build using VS 2008.

I would be happy to work with you in developing a build configuration.

I would suggest the addition of a NETCF conditional variable, which could also require the NET35 variable be set, or could be used as an alternative to NET35 or NET40.

**Comment by theraot** [comment]
I have set a build configuration that defines both NETCF and NET35, that targets .NET 3.5 and is set to use C# 3 - it is available on the branch v1_netcf

I will review and fix the code for C# 3 - after that I'll publish the code and let you know so you can test it and see if anything is missing or not working properly

**Comment by oznetmaster** [comment]
That is great.  As soon as you publish it, I will run the unit tests and make sure that all is ok.

I have the NUnit for CF so I can actually test in the CF environment.

**Comment by theraot** [comment]
Just published the code. As I said, it is on the v1_netcf branch, here: https://github.com/theraot/Theraot/tree/v1_netcf

I have also updated the build scripts to include NET35-CF in the NuGet package

**Comment by theraot** [comment]
The build configuration NET35-CF is building in Visual Studio 2008 - although Visual Studio 2008 says it is targeting .NET 2.0 regardless of what I do... it is actually targeting .NET 3.5

Now, how do I setup Compact Framework and how do write project files to target it?

**Comment by theraot** [comment]
@oznetmaster 

The build configuration NET35-CF is building in Visual Studio 2008 - although Visual Studio 2008 says it is targeting .NET 2.0 regardless of what I do... it is actually targeting .NET 3.5

Now, how do I setup Compact Framework and how do write project files to target it?

**Comment by theraot** [comment]
@oznetmaster I just released the NET35-CF build on the last nuget package - it is build to target .NET 3.5 - will you be able to test that?

**Comment by oznetmaster** [comment]
There is no nuget for VS2008 :(

**Comment by theraot** [comment]
@oznetmaster will the article [NuGet Support for Visual Studio 2008](http://www.hanselman.com/blog/NuGetSupportForVisualStudio2008.aspx) by Scott Hanselman help?

**Comment by theraot** [comment]
@oznetmaster updated the package. Regardless, here is a [Direct link for the binary](https://ci.appveyor.com/api/buildjobs/2c8qs1jl3wa5xcp7/artifacts/package%2Flib%2FNET35-CF%2FTheraot.Core.dll) from Appveyor.

**Comment by theraot** [comment]
The code to allow the project on visual studio 2008 is messing the automated built. So, I'm going back to the old code and removing the solution for visual studio 2008.

**Comment by theraot** [comment]
I am moving away from keeping old versions of C#.
