### ISSUE TITLE
SemaphoreSlim Constructor #1 Doesn't Follow MSDN Guidelines

### ISSUE THREAD

**Issue by Kleptine** [theraot/Theraot#19]
The first constructor for SemaphoreSlim has the following requirement:

"The initialCount parameter defines the number of concurrent requests to enter the semaphore that can be granted. However, it doesn’t define the maximum number of requests that can be granted concurrently. A SemaphoreSlim object instantiated by calling this constructor doesn’t throw a SemaphoreFullException exception if a call to the Release method increases the value of the CurrentCount property beyond initialCount. This occurs if there are more calls to Release methods than there are to Wait or WaitAsync methods. "

https://msdn.microsoft.com/en-us/library/dd270887(v=vs.110).aspx

However in the Theraot implementation, SemaphoreFullException is called regardless of which constructor is used. (See SemaphoreSlim.Release()).

Spent a while tracking this one down!

**Comment by theraot** [comment]
Thank you for reporting this. I will be working on a fix, a new version should be out in the next few ours.

**Comment by theraot** [comment]
I just deployed a new nuget with the fixes for SemaphoreSlim. I also reviwed the whole class and added new tests for it.

Don't hesitate to post a new issue if you find more problems with it. Thanks again for reporting this.

I'm closing the issue.

**Comment by Kleptine** [comment]
Wow! Incredibly fast thanks!
