### ISSUE TITLE
Build improvements

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#26]
Instead of having #if NET20 || NET30 , it is better to introduce LESSTHAN_NET35 .
You can check build props from CodeJam library https://github.com/rsdn/CodeJam/blob/master/Build/Props/CodeJam.Targeting.props .
IMO it is more elegant.

**Comment by theraot** [comment]
I have been considering that if I start defining custom compilation constants I should probably make it SUPPORTS_XXX

I want to note that things are as clear cut when it comes to .NET Standard, it has sometimes moved backwards, see for example [BlockingCollection<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1); it is available on .NET Standard 1.4 and .NET Standard 1.6 but not on .NET Standard 1.5. By the way, I haven't got around to test that (testing on .NET Standard has been problematic).

I will get to this.

**Comment by theraot** [comment]
I have added LESSTHAN, TARGETS and even GREATERTHAN (because reasons) compilation constants.
