### ISSUE TITLE
Enumerable.Zip .NET 3.5

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#31]
Enumerable.Zip doesn't exist in .NET 3.5 but the library defines it only for 2.0 and 3.0.
[Enumerable.net30](https://github.com/theraot/Theraot/blob/master/Framework.Core/System/Linq/Enumerable.net30.cs#L1)

[Enumerable.Zip](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?redirectedfrom=MSDN&view=netframework-4.0)

**Comment by theraot** [comment]
It is currently in Theraot.Collections.Extensions.Zip

Although, I am planning to move it to a new System.Linq.EnumerableEx.Zip so you do not need a new using directive just for it.

I am closing this.
