### ISSUE TITLE
Move extension methods to System

### ISSUE THREAD

**Issue by theraot** [theraot/Theraot#40]
Extension methods used as workaround to provide missing functionality will be moved to the same namespace of the extended type within a static class with the suffix "TheraotExtensions".

These classes are not meant to be referenced directly, and will only have extension methods.

The verbose name should avoid any potential future conflicts.

**Comment by NN---** [comment]
What about namespace Theraot { static class Extensions { 
That way you can add more classes in the future under this namespace?

**Comment by theraot** [comment]
@NN--- I have a Theraot namespace already, and there are more classes there. Although there is little waste, you can find plenty of useful things there.

However, the idea is to move the extensions that you need to get your code to work, nothing else. That is a small fraction of the code under the Threaot namespace.

**Comment by theraot** [comment]
I moved all the extension methods I wanted to move
