### ISSUE TITLE
Do not use GC.KeepAlive to prevent warnings

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#43]
Instead of using GC.KeepAlive to suppress warnings, just use suppression comment.
Or introduce method No.Op with Conditional("never") and agressive inlining, which does nothing and suppresses warning.

Examples:

```cs
class ExtendedDictionary {
        protected ExtendedDictionary(SerializationInfo info, StreamingContext context)
#if GREATERTHAN_NETCOREAPP20 || NETSTANDARD2_0 || TARGETS_NET
            : base(info, context)
            : base(info, context)
#endif
        {
        {
            // Empty
            // TODO ?
            GC.KeepAlive(info);
            GC.KeepAlive(context);
        }
        }
}


class Volatile {
        public static void Write<T>(ref T location, T value)
            where T : class
        {
            GC.KeepAlive(Interlocked.Exchange(ref location, value));
        }
}
```

**Comment by theraot** [comment]
Note that with conditional the compiler will not emit the call, the JIT would have nothing to inline ([demo](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgoGYECY4DCcA3hnOQjlACxwCyAFAJQlkXsBuAhgE5wAecALxxEuNOnbsAcgHsAdAHkADg35MJUikgCcajW3IBfDCfQYAlgDsALgFMeVrgBsEiAGx44cjKUkUAbSR5ABELLgBzK1kAZxsLAGMY+QJZK2ALeLSXBgAiaQBRADUCgCVcpgBdQ0o3Txo4FQAeABUAPgYWuF4Iphq/djMjIA===)).

**Comment by NN---** [comment]
Ok just call it THERAOT_NEVER to prevent collisions:)

Perhaps this can be useful utility class in CodeJam

**Comment by theraot** [comment]
@NN--- sure THERAOT_NEVER, writing now.

**Comment by theraot** [comment]
I have gone over all GC.KeepAlive and decided on which should be converted to Theraot.No.Op and which should not, also did a few tweaks along the way, including marking deprecated those serialization constructors.

**Comment by NN---** [comment]
I still see a lot of GC.KeepAlive especially in tests which ignores the value:
E.g.
```cs
        protected override void QueueTask(Task task)
        {
            GC.KeepAlive(task);
        }
```

My opinion is that you should check all GC.KeepAlive and leave only those that you really really need.
Please reconsider removing all of them and use your No.Op or just suppression comment when you just want to ignore expression's value.
