### ISSUE TITLE
Safe classes

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#46]
Please rename Safe** classes such as SafeQueue to more meaningful.
The word Safe (as well as Fast, Simple etc.) is too ambiguous.
If you want to refer as thread-safe collection then call it ThreadSafeQueue.

For instance, for me 'Safe' means doesn't receive nulls or has some input vasodilations.

**Comment by theraot** [comment]
Ok, I will rename them

**Comment by theraot** [comment]
They have been renamed.
