### ISSUE TITLE
Ambiguous StringEx

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#47]
StringEx defined both in System and in Theraot.Core namespaces.
I guess the intend that you use only one but System namespace is too common and used almost in every file.

**Comment by theraot** [comment]
You are the one naming them both StringEx in your pull request #50 They are System.StringEx and Theraot.Core.StringHelper. See: https://github.com/theraot/Theraot/pull/50/commits/e3a3a8e64957e263805fde44fef6516261ea58b9#diff-53449914acd6641b2e1c2556a284b6d2L18

I think you try to fix Test build, I will do it.
