### ISSUE TITLE
Using System namespace in tests is not a good idea

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#48]
For instance here:
https://github.com/theraot/Theraot/blob/fa814fedc9f94d3d6d43f9bffd3703f9515bf1bb/Tests/System/IntPtrTest.cs#L6

The problem arises when you have other file which wants to use System namespace:

```cs
namespace Tests.Theraot.Core
{
  class A 
  {
    void F() { System.String a = ""; } // Compilation error, String is not in Tests.System namespace

    void G() { global::System.String a = ""; } // OK, but too ugly
  }
}
```

**Comment by theraot** [comment]
Noted, I will get to it.

**Comment by NN---** [comment]
Is it done already?

**Comment by theraot** [comment]
No,

Tests in my big technical debt. See for example #108

I wanted to make a new project, migrate test by test. Lost motivation after NUnit got - kind of※ - fixed. 

※: Below .NET Standard 1.3 it does not work. Yet, we let it be, I do not think any testing framework works there.
