### ISSUE TITLE
Missing ToString(IFormatProvider)

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#64]
.NET Standard 1.6 and below with .NET Core 1.1 and below doen't have ToString(IFormatProvider) for basic types such as Char, Int32 ...

Implementation for Char:
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Char.cs#L157

**Comment by NN---** [comment]
What about other basic types ?
Long, short and so on ?

**Comment by theraot** [comment]
As far as I can tell they have this overload
