### ISSUE TITLE
EnumTheraotExtensions.HasFlag doesn't test for null correctly

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#77]
```cs
        public static bool HasFlag(this Enum value, Enum flag)
        {
            //Added in .NET 4.0
            var type = value.GetType();
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }
```

The check should be before the use.

**Comment by theraot** [comment]
It used to go on and pretend it wasn't null, which would result in a NullReferenceException, which is what you would get if you called on null on targets that have the method (and didn't use the extension method).

However, let us check correctly.

**Comment by NN---** [comment]
Then add the relevant test and fix my change.

**Comment by theraot** [comment]
That I'm doing

**Comment by NN---** [comment]
Is it possible to invoke HasFlag with null instance ?
Any enum is a value type so the only way is to cast to System.Enum but then you get NRE due to callvirt instruction and not from HasFlag method.

**Comment by theraot** [comment]
Right, casting to Enum is the only way. And that results in NullReferenceException on targets that has HasFlag.

However the extension method does not have that problem, it will run even if you pass null. If somebody out there is using HasFlag and programming agaist the NullReferenceException - which, arguebly, they should not do - they would not get it.

They should not pass null to HasFlag, right? On that order of ideas, the check is a waste.

But, no. Let us check correctly. People - including me - should not look at the code and think I forgot about null.

Yeah, user code "should not" throw NullReferenceException... I do not really care, the code already uses other thing that Microsoft exposes yet claim we should not use.

**Comment by NN---** [comment]
I see. No problems let's have the same behavior.
Can you modify test to be the same for all frameworks ?

**Comment by theraot** [comment]
This is already in source, nuget soon.
