### ISSUE TITLE
Upgrade library to C# 7.3

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#78]
This allows using enum constraint:
https://blog.jetbrains.com/dotnet/2018/07/19/unmanaged-delegate-enum-type-constraints-c-7-3-rider-resharper/

**Comment by theraot** [comment]
Code is now C# 8.0 - however, I do not think I will be using the enum contraint. Not for HasFlag or TryParse, they will keep close to the signature in the BCL.
