### ISSUE TITLE
Delegate.CreateDelegate for .NET Standard 1.6 and below

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#81]
Possible implementation:

```cs
MethodInfo methodInfo = target.GetType().GetMethod(nameof(FooMethod));

Action action = (Action) methodInfo.CreateDelegate(typeof(Action), target);
```

https://stackoverflow.com/questions/43865841/delegate-does-not-contain-a-definition-for-createdelegate-in-net-core

MethodInfoTheraotExtensions should be defined for .NET Standard <2.0

**Comment by theraot** [comment]
"MethodInfoTheraotExtensions should be defined for .NET Standard <2.0"

Nope, this is where you find it:

.NET 2.0 to 4.0: Theraot.Core
.NET 4.5+: mscorlib
.NET Core 1.0 to 1.1: System.Reflection
.NET Core 2.0+: System.Runtime
.NET Standard: System.Reflection

**Comment by NN---** [comment]
Can you show the usage ?
I have code Delegate.CreateDelegate .
How I make  compile happy with minimal changes ?

**Comment by theraot** [comment]
In doubt, check http://packagesearch.azurewebsites.net/

**Comment by NN---** [comment]
I use this for API search: https://apisof.net/
There is workaround as I showed in the issue.
It would be nice to have DelegateEx.CreateDelegate for instance.

**Comment by theraot** [comment]
DelegateEx could be. See also Theraot.Reflection.DelegateBuilder

**Comment by theraot** [comment]
Reopening for DelegateEx

**Comment by theraot** [comment]
As far as I can tell, I need to add a reference to System.Reflection to Framework.Core just for DelegateEx, I'm not doing it.
