### ISSUE TITLE
System.Converter for .NET Standard 1.6 and below

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#83]
```cs
public delegate TOutput Converter<in TInput, out TOutput>(TInput input);
```

https://docs.microsoft.com/en-us/dotnet/api/system.converter-2?view=netframework-4.7.2

https://github.com/dotnet/coreclr/blob/a9b57bd4fe194b30b3c6e9a85a316fc218f474be/src/System.Private.CoreLib/shared/System/Action.cs#L29

**Comment by theraot** [comment]
Added in source
