### ISSUE TITLE
Include ReflectionBridge into Theraot

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#85]
This should be part of Theraot library
https://github.com/StefH/ReflectionBridge

**Comment by NN---** [comment]
Improved version: https://github.com/NN---/CodeJam/blob/legacy_dotnet_targetting/CodeJam.Main/Targeting/NETSTANDARD16/TypeExtensions.cs

**Comment by theraot** [comment]
System.Reflection.TypeExtensions

**Comment by NN---** [comment]
It is defined only for 1.3
#if LESSTHAN_NETSTANDARD13

You can add  also overload for Type with simpler implementation than MemberInfo.

I think some overloads are missing like GetCustomAttributes.

**Comment by theraot** [comment]
Some things are missing, like #82

**Comment by NN---** [comment]
Currently I am using my version.
I will gladly switch to Therapy once you add all extension methods.

**Comment by NN---** [comment]
Do you want to open issue for each overload separately or just reopen this one ?
